lang: english

mechanics:
  perfect-chance: 0.3
  splash-time: 80
  starter-recipes:
    - custardpie
    - tomatosoup
    - carrotsoup
    - seedsoup
    - pumpkinsoup
    - cactussoup
    - potatosoup
  namespace: 'customcooking'
  failure-item: 'failureitem'
  unlit-cooking-pot: 'cooking_pot_unlit'
  lit-cooking-pot: 'cooking_pot_lit'
  pot-effect: 'pot_effect'

gui:
  config:
    recipe-book: 'customcooking:recipe_book'
    mastery-line: "<!italic><#ff9900>Mastery [{mastery}]"
    mastery-bar: "<!italic><#ffcc33>[{bar}<#ffcc33>]"
    mastery-true: "<!italic><#ffcc99>This item has been mastered /<!italic><#ffcc99>and will be cooked automatically."
    mastery-false: "<!italic><#ffcc99>This dish has not been mastered /<!italic><#ffcc99>and will have to be manually cooked."
    ingredients-line: "<!italic><#ffcc33>Ingredients:"
    info-cook: "<!italic><#ffcc33>[Click] <#ffcc99>to Cook"
    info-right-cook: "<!italic><#ffcc33>[Right Click] <#ffcc99>to Cook"
    info-left-cook: "<!italic><#ffcc33>[Left Click] <#ffcc99>to Autocook"
  items:
    unknown-item: 'unknownrecipe'
    grinder-item: 'grinder'


titles:
  success:
    title:
      - '<green>Success!</green>'
      - '<green>GG!</green>'
      - '<green>Good Job!</green>'
    subtitle:
      - 'You have made a {recipe}'
      - "Whoa! Well done!"
      - '{recipe} Well done!'
    fade:
      # ticks
      in: 10
      stay: 30
      out: 10
  failure:
    title:
      - '<red>Be more concentrated!</red>'
      - '<red>Failure!</red>'
      - '<red>What a pity!</red>'
      - '<red>Try next time!</red>'
    subtitle:
      - 'The dish burned!'
      - 'Pay more attention to it!'
      - 'Blame it on the lag'
    fade:
      in: 10
      stay: 30
      out: 10