lang: english

mechanics:
  perfect-chance: 30
  splash-time: 100
  starter-recipes:
    - recipe1
    - recipe2
    - recipe3

titles:
  success:
    title:
      - '<green>Success!</green>'
      - '<green>GG!</green>'
      - '<green>Good Job!</green>'
    subtitle:
      - 'You have made a {recipe}'
      - "Whoa! Well done!"
      - '{recipe} Well done!'
    fade:
      # ticks
      in: 10
      stay: 30
      out: 10
  failure:
    title:
      - '<red>Be more concentrated!</red>'
      - '<red>Failure!</red>'
      - '<red>What a pity!</red>'
      - '<red>Try next time!</red>'
    subtitle:
      - 'The dish burned!'
      - 'Pay more attention to it!'
      - 'Blame it on the lag'
    fade:
      in: 10
      stay: 30
      out: 10