name: CustomCooking
version: '${project.version}'
main: plugin.customcooking.CustomCooking
author: [ SnowyOwl217 ]
api-version: 1.18
depend:
  - ProtocolLib
  - PlaceholderAPI
  - NBTAPI
softdepend:
  - ItemsAdder
  - HolographicDisplays

commands:
  cooking:
    description: The main plugin command

permissions:
  customcooking.*:
    default: false
  customcooking.admin:
    default: op