name: CustomCooking
version: '${project.version}'
main: plugin.customcooking.CustomCooking
author: [ SnowyOwl217 ]
api-version: 1.18
depend:
  - ProtocolLib
  - PlaceholderAPI
softdepend:
  - ItemsAdder

commands:
  cooking:
    description: The main plugin command
    permission: customcooking.admin

permissions:
  customcooking.*:
    default: false
  customcooking.admin:
    default: op
  customcooking.player:
    children:
      - customcooking.recipe.custardpie
      - customcooking.recipe.tomatosoup
      - customcooking.recipe.carrotsoup
      - customcooking.recipe.seedsoup
      - customcooking.recipe.applepie
      - customcooking.recipe.pumpkinsoup
      - customcooking.recipe.cactussoup
      - customcooking.recipe.potatosoup
    default: false